"""add_dados_extraidos_to_emaillog

Revision ID: a88e251f1f3a
Revises: 30a165f5b2e6
Create Date: 2026-04-19 15:43:22.426826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a88e251f1f3a'
down_revision: Union[str, Sequence[str], None] = '30a165f5b2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Comentado tudo que exige Verificação/Lock longo para evitar Timeout na VPS
    # op.execute("DROP TABLE IF EXISTS database_fornecedores CASCADE")
    
    # op.alter_column('concessionarias_vinculadas', 'leitura_individualizada',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    # op.alter_column('condominios', 'leitura_individualizada_ativa',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('false'))
    
    # Comentado para evitar conflitos com dados duplicados durante o boot
    # op.create_index(op.f('ix_condominios_cnpj'), 'condominios', ['cnpj'], unique=False)
    op.add_column('email_logs', sa.Column('dados_extraidos', sa.JSON(), nullable=True))
    op.alter_column('faturas', 'debito_automatico',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('historico_faturas', sa.Column('pdf_nome_original', sa.String(length=255), nullable=True))
    op.alter_column('historico_faturas', 'debito_automatico',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table_comment(
        'historico_faturas',
        existing_comment='This is a duplicate of faturas',
        schema=None
    )
    op.drop_index(op.f('idx_user_condominios_condo'), table_name='user_condominios')
    op.drop_index(op.f('idx_user_condominios_user'), table_name='user_condominios')
    op.drop_constraint(op.f('user_condominios_user_id_condominio_id_key'), 'user_condominios', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('user_condominios_user_id_condominio_id_key'), 'user_condominios', ['user_id', 'condominio_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_condominios_user'), 'user_condominios', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_condominios_condo'), 'user_condominios', ['condominio_id'], unique=False)
    op.create_table_comment(
        'historico_faturas',
        'This is a duplicate of faturas',
        existing_comment=None,
        schema=None
    )
    op.alter_column('historico_faturas', 'debito_automatico',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('historico_faturas', 'pdf_nome_original')
    op.alter_column('faturas', 'debito_automatico',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('email_logs', 'dados_extraidos')
    op.drop_index(op.f('ix_condominios_cnpj'), table_name='condominios')
    op.create_index(op.f('ix_condominios_cnpj'), 'condominios', ['cnpj'], unique=False)
    op.alter_column('condominios', 'leitura_individualizada_ativa',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('concessionarias_vinculadas', 'leitura_individualizada',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.create_table('database_fornecedores',
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('nomeFornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('documentoFornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('e-mailFornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('whatsappFornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categoriaFornecedor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('motivoInativo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('administradora', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('database_fornecedores_created_by_id_fkey'))
    )
    # ### end Alembic commands ###
